<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#data-source" data-toc-modified-id="data-source-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>data source</a></span></li></ul></div>

In [1]:
from arcgis.gis import GIS
trailheads_id = '883cedb8c9fe4524b64d47666ed234a7'
gis = GIS()
trailheads_item = gis.content.get(trailheads_id)
trailheads_item
m = gis.map()
m.add_layer(trailheads_item)

In [2]:
type(m)

arcgis.widgets._mapview.MapView

In [3]:
m

MapView(layout=Layout(height='400px', width='100%'))

In [3]:
m.center = [34.09042, -118.71511]           # `[latitude, longitude]`
m.zoom = 11

In [19]:
import pandas as pd
df = pd.read_csv('../data/12-11-2020.csv')
df.describe()

,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,Incident_Rate,Total_Test_Results,People_Hospitalized,Case_Fatality_Ratio,UID,Testing_Rate,Hospitalization_Rate
count,56.000000,56.000000,5.800000e+01,58.000000,4.800000e+01,5.800000e+01,58.000000,56.000000,5.600000e+01,0.0,57.000000,5.800000e+01,56.000000,0.0
mean,36.840089,-85.206614,2.731515e+05,5093.965517,1.278190e+05,1.622763e+05,3288.086207,4854.518937,3.810423e+06,NaN,1.724010,7.676194e+07,66418.707957,NaN
std,10.887035,49.754449,3.168640e+05,6894.742996,1.903550e+05,2.702915e+05,17408.350591,2243.695109,4.994566e+06,NaN,0.897344,2.378302e+07,32871.720055,NaN
min,-14.271000,-170.132000,0.000000e+00,0.000000,2.900000e+01,0.000000e+00,1.000000,0.000000,2.140000e+03,NaN,0.000000,1.600000e+01,3846.084722,NaN
25%,34.594600,-101.165775,6.072825e+04,839.750000,1.425975e+04,1.138450e+04,18.250000,3764.338271,8.965430e+05,NaN,1.259010,8.400001e+07,42722.189641,NaN
50%,39.061850,-87.944200,1.919360e+05,2677.000000,5.591350e+04,7.044350e+04,32.500000,4875.503918,2.117280e+06,NaN,1.582941,8.400003e+07,63678.623553,NaN
75%,42.361650,-76.970625,3.854340e+05,5654.750000,1.842172e+05,1.895512e+05,47.750000,6188.425060,4.687285e+06,NaN,1.905589,8.400004e+07,80606.056204,NaN
max,61.370700,145.673900,1.516215e+06,35357.000000,1.157334e+06,1.495428e+06,99999.000000,11444.475646,2.657234e+07,NaN,4.690271,8.410000e+07,162132.360923,NaN

### data source
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

In [20]:
df.head(10)

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,Incident_Rate,Total_Test_Results,People_Hospitalized,Case_Fatality_Ratio,UID,ISO3,Testing_Rate,Hospitalization_Rate
0,Alabama,US,2020-12-12 05:30:32,32.3182,-86.9023,288775,4086,174805.0,109884.0,1.0,5889.539146,1696439.0,NaN,1.414942,84000001.0,USA,34598.714917,NaN
1,Alaska,US,2020-12-12 05:30:32,61.3707,-152.4044,39975,158,7165.0,32652.0,2.0,5464.462200,1123545.0,NaN,0.395247,84000002.0,USA,153585.220321,NaN
2,American Samoa,US,2020-12-12 05:30:32,-14.2710,-170.1320,0,0,NaN,0.0,60.0,0.000000,2140.0,NaN,NaN,16.0,ASM,3846.084722,NaN
3,Arizona,US,2020-12-12 05:30:32,33.7298,-111.4312,394512,7245,59932.0,327335.0,4.0,5420.076093,2460821.0,NaN,1.836446,84000004.0,USA,33808.444538,NaN
4,Arkansas,US,2020-12-12 05:30:32,34.9697,-92.3731,181624,2875,158018.0,20731.0,5.0,6018.416040,1828179.0,NaN,1.582941,84000005.0,USA,60579.779204,NaN
5,California,US,2020-12-12 05:30:32,36.1162,-119.6816,1516215,20787,NaN,1495428.0,6.0,3837.331552,26572343.0,NaN,1.370980,84000006.0,USA,67250.944094,NaN
6,Colorado,US,2020-12-12 05:30:32,39.0598,-105.3111,281673,3846,15027.0,262800.0,8.0,4891.229603,3691463.0,NaN,1.365413,84000008.0,USA,64101.966126,NaN
7,Connecticut,US,2020-12-12 05:30:32,41.5978,-72.7554,146761,5363,9800.0,131598.0,9.0,4116.386703,3695091.0,NaN,3.654241,84000009.0,USA,103640.772819,NaN
8,Delaware,US,2020-12-12 05:30:32,39.3185,-75.5071,43818,807,18851.0,24160.0,10.0,4499.858282,819158.0,NaN,1.841709,84000010.0,USA,84122.847014,NaN
9,Diamond Princess,US,2020-12-12 05:30:32,NaN,NaN,49,0,NaN,49.0,88888.0,NaN,NaN,NaN,0.000000,84088888.0,USA,NaN,NaN

so the unique identifier is province/state, and magnitude is handled by each column
i guess a dataset of "lat/long of each person" would be much harder to record. which locations are you going to denote, their exact address?

In [22]:
len(df)

58

In [23]:
df.columns

Index(['Province_State', 'Country_Region', 'Last_Update', 'Lat', 'Long_',
       'Confirmed', 'Deaths', 'Recovered', 'Active', 'FIPS', 'Incident_Rate',
       'Total_Test_Results', 'People_Hospitalized', 'Case_Fatality_Ratio',
       'UID', 'ISO3', 'Testing_Rate', 'Hospitalization_Rate'],
      dtype='object')

In [24]:
df.nunique()

Province_State          58
Country_Region           1
Last_Update              1
Lat                     56
Long_                   56
Confirmed               58
Deaths                  57
Recovered               48
Active                  58
FIPS                    58
Incident_Rate           56
Total_Test_Results      56
People_Hospitalized      0
Case_Fatality_Ratio     57
UID                     58
ISO3                     6
Testing_Rate            56
Hospitalization_Rate     0
dtype: int64